services:
  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./redux
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

